import { BOMItem } from '../types';

export const SYSTEM_SPECS = {
  name: "SAFE BREATH",
  tagline: "Smart Multi-Gas Detection & Air Quality Monitoring System",
  descriptor: "A low-cost, connected atmospheric safety system for detecting hazardous gases and monitoring environmental conditions in real time.",
  version: "Hardware Prototype v1.2",
  firmwareBaseline: {
    mq135BaselineADC: 49.81,
    mq6BaselineADC: 14.82,
    loadResistorRL: 1.0, // kOhm
    sampleRateHz: 2,
    telemetryBroadcastRateSec: 3,
  },
  thresholds: {
    co: {
      sensor: "ZE07-CO",
      technology: "Electrochemical potentiostatic cell",
      unit: "ppm",
      safeMax: 35,
      warnThreshold: 35,
      dangerThreshold: 70,
      hysteresis: 5,
      healthRange: [0, 500],
      responseLatencyMs: 350,
      description: "Colorless, odorless asphyxiant generated by incomplete combustion in heaters, stoves, and engines."
    },
    voc: {
      sensor: "MQ-135",
      technology: "SnO2 semiconductor surface catalysis",
      unit: "ppm",
      safeMax: 200,
      warnThreshold: 200,
      dangerThreshold: 400,
      hysteresis: 20,
      healthRange: [10, 1000],
      responseLatencyMs: 800,
      description: "Airborne chemicals (benzene, alcohol, smoke, ammonia, formaldehydes) affecting respiratory health."
    },
    lpg: {
      sensor: "MQ-6",
      technology: "Heated SnO2 tin-dioxide ceramic probe",
      unit: "ppm",
      safeMax: 500,
      warnThreshold: 500,
      dangerThreshold: 1500,
      hysteresis: 50,
      healthRange: [200, 10000],
      responseLatencyMs: 500,
      description: "Propane/butane liquefied petroleum gas; highly combustible explosive hazard at lower explosive limits (LEL)."
    },
    temperature: {
      sensor: "DHT11",
      technology: "NTC thermistor + resistive humidity sensing",
      unit: "°C",
      alarmThreshold: 45,
      clearThreshold: 40,
      description: "Thermal runaway or fire detection indicator with a 5°C safety hysteresis band."
    }
  }
};

export const BILL_OF_MATERIALS: BOMItem[] = [
  {
    component: "ESP32 DevKit V1",
    subsystem: "Processing",
    partNumber: "ESP32-WROOM-32D",
    estimatedCostUsd: 4.80,
    purpose: "Main central controller: safety state evaluation, OLED rendering, local alarm PWM, diagnostics"
  },
  {
    component: "Arduino Nano V3",
    subsystem: "Processing",
    partNumber: "ATmega328P CH340",
    estimatedCostUsd: 3.20,
    purpose: "Dedicated sensor acquisition: continuous analog sampling of MQ-135, MQ-6 and DHT11 digital bitstream"
  },
  {
    component: "ESP32-CAM Gateway",
    subsystem: "Gateway & Display",
    partNumber: "AI-Thinker ESP32-CAM",
    estimatedCostUsd: 5.50,
    purpose: "Wireless gateway & offline logger: 802.11 b/g/n Wi-Fi, MicroSD FAT32 circular log buffer, Supabase sync"
  },
  {
    component: "ZE07-CO Electrochemical Module",
    subsystem: "Sensors",
    partNumber: "Winsen ZE07-CO",
    estimatedCostUsd: 14.50,
    purpose: "High-precision electrochemical CO sensor with digital UART output (0–500 ppm, 0.1 ppm resolution)"
  },
  {
    component: "MQ-135 Air Quality Sensor",
    subsystem: "Sensors",
    partNumber: "MQ-135 SnO2 Module",
    estimatedCostUsd: 2.10,
    purpose: "Broadband volatile organic compounds (VOC), NH3, NOx, alcohol, benzene, smoke detection"
  },
  {
    component: "MQ-6 Combustible Gas Sensor",
    subsystem: "Sensors",
    partNumber: "MQ-6 SnO2 Module",
    estimatedCostUsd: 2.20,
    purpose: "Liquefied Petroleum Gas (LPG), isobutane, propane and natural gas detection"
  },
  {
    component: "DHT11 Climate Sensor",
    subsystem: "Sensors",
    partNumber: "DHT11 Single-Bus Digital",
    estimatedCostUsd: 1.40,
    purpose: "Ambient temperature (0–50°C) and relative humidity (20–90% RH) environmental compensation"
  },
  {
    component: "0.96\" I2C OLED Display",
    subsystem: "Gateway & Display",
    partNumber: "SSD1306 128x64 White",
    estimatedCostUsd: 2.60,
    purpose: "Immediate at-a-glance physical telemetry: real-time gas levels, warning states, and diagnostic status"
  },
  {
    component: "Active Piezo Buzzer 5V",
    subsystem: "Gateway & Display",
    partNumber: "TMB12A05 85dB",
    estimatedCostUsd: 0.60,
    purpose: "Autonomous physical acoustic alarm, pulses at 2.4 kHz with distinct warning/danger sound cadences"
  },
  {
    component: "MicroSD Card 16GB Class 10",
    subsystem: "Gateway & Display",
    partNumber: "SanDisk Ultra 16GB",
    estimatedCostUsd: 3.80,
    purpose: "Non-volatile local telemetry persistence and offline event logging"
  },
  {
    component: "5V 2.5A Buck Regulator & Passives",
    subsystem: "Power & Passive",
    partNumber: "LM2596 + 1.0kΩ RL + Filtering",
    estimatedCostUsd: 2.40,
    purpose: "Heater power rail stabilization (MQ sensors require ~800mW heater currents) and noise filtering"
  }
];

export const CONTROLLER_ARCHITECTURE_ROLES = [
  {
    controller: "Arduino Nano",
    role: "Dedicated Sensor Acquisition Subsystem",
    frequency: "100 Hz ADC loop, averaged to 2 Hz",
    responsibilities: [
      "Continuous analog reading of MQ-135 and MQ-6 gas sensors via 10-bit ADC",
      "Single-wire timing decoding for DHT11 temperature and humidity frame",
      "Moving average digital filter to suppress electrical noise and heater switching spikes",
      "Packetizes raw sensor measurements with sequence IDs and checksums into a UART packet stream"
    ],
    whySeparate: "Prevents high-priority Wi-Fi network interrupts or display rendering routines from disrupting microsecond-sensitive DHT11 timing and analog ADC conversions."
  },
  {
    controller: "ESP32 DevKit",
    role: "Central Safety & Local Control Subsystem",
    frequency: "Dual-Core 240 MHz, Core 1 Safety / Core 0 UI",
    responsibilities: [
      "Receives and validates incoming sensor packets from Arduino Nano over HardwareSerial",
      "Direct UART interface to ZE07-CO electrochemical module",
      "Evaluates multi-gas safety state machine (SAFE, WARNING, DANGER) with threshold hysteresis",
      "Autonomous hardware driver for 85 dB Piezo Buzzer (immediate zero-latency alarm)",
      "Renders dynamic telemetry screens on the 128x64 monochrome OLED display",
      "Maintains sensor health monitors: checks for stale data, disconnection, and baseline drift"
    ],
    whySeparate: "Keeps life-safety critical decision loops completely isolated from network failures, cloud latency, or Wi-Fi handshake drops."
  },
  {
    controller: "ESP32-CAM",
    role: "Gateway, Storage & Cloud Synchronization Subsystem",
    frequency: "Wi-Fi 802.11 b/g/n + SPI MicroSD Bus",
    responsibilities: [
      "MicroSD local data logging in CSV format for offline safety analysis",
      "Wi-Fi connection management with automated reconnection and packet retry queues",
      "Secure HTTPS/REST or Supabase Realtime ingestion channel for environmental telemetry",
      "Triggers remote notification dispatch (Firebase Cloud Messaging) for off-site awareness"
    ],
    whySeparate: "If the local router loses power or internet connectivity drops, the gateway queues data while the local alarm and OLED continue protecting nearby occupants without hesitation."
  }
];

export const HARDWARE_PINS = [
  { bus: "UART1 (Nano -> ESP32)", source: "Arduino Nano TX (D1)", destination: "ESP32 RX2 (GPIO16)", purpose: "Sensor raw telemetry packet transmission (9600 baud, 8N1)" },
  { bus: "UART2 (ZE07 -> ESP32)", source: "ZE07-CO TX", destination: "ESP32 RX1 (GPIO18)", purpose: "Electrochemical digital CO concentration stream (9600 baud)" },
  { bus: "I2C Bus", source: "ESP32 GPIO21 (SDA) / GPIO22 (SCL)", destination: "SSD1306 OLED", purpose: "128x64 display refresh at 10 FPS" },
  { bus: "GPIO PWM", source: "ESP32 GPIO23", destination: "Piezo Buzzer Transistor Driver", purpose: "Acoustic alarm trigger (2.4 kHz PWM, non-blocking)" },
  { bus: "Analog In", source: "MQ-135 Vout", destination: "Arduino Nano A0", purpose: "VOC concentration voltage reading across 1.0 kΩ RL" },
  { bus: "Analog In", source: "MQ-6 Vout", destination: "Arduino Nano A1", purpose: "LPG concentration voltage reading across 1.0 kΩ RL" },
  { bus: "1-Wire Digital", source: "DHT11 Data", destination: "Arduino Nano D2", purpose: "Temperature/Humidity 40-bit pulse width stream" },
  { bus: "SPI Bus", source: "ESP32-CAM HSPI", destination: "Onboard MicroSD Slot", purpose: "FAT32 file logging (/logs/safebreath_YYYYMMDD.csv)" }
];

export const HARDWARE_COMPONENTS = [
  {
    id: "ze07-co",
    name: "ZE07-CO",
    title: "Electrochemical Carbon Monoxide Sensor",
    category: "sensor",
    role: "Monitors toxic, odorless CO gas via catalytic oxidation on an electrochemical cell.",
    dataProduced: "Calibrated 0–500 ppm digital concentration stream (0.1 ppm resolution)",
    dataDestination: "Direct UART link to ESP32 DevKit RX1 (GPIO18)",
    busType: "UART (9600 Baud, 8N1)",
    specs: "Response time < 30s · Working range 0–500 ppm · Low power draw (< 5mA)"
  },
  {
    id: "mq-135",
    name: "MQ-135",
    title: "Air Quality & Broadband VOC Sensor",
    category: "sensor",
    role: "Detects volatile organic compounds, benzene, alcohol, smoke, ammonia, and air pollutants.",
    dataProduced: "Variable analog resistance (0–1023 ADC) across 1.0 kΩ RL load resistor",
    dataDestination: "Arduino Nano Analog Input A0",
    busType: "Analog Voltage (0.0 – 5.0 V)",
    specs: "SnO2 semiconductor surface · 10–1000 ppm sensitivity · 49.81 ADC clean air baseline"
  },
  {
    id: "mq-6",
    name: "MQ-6",
    title: "Liquefied Petroleum Gas (LPG) Sensor",
    category: "sensor",
    role: "High-selectivity detection of combustible propane, butane, and isobutane gases.",
    dataProduced: "Analog voltage proportional to combustible gas partial pressure",
    dataDestination: "Arduino Nano Analog Input A1",
    busType: "Analog Voltage (0.0 – 5.0 V)",
    specs: "SnO2 micro-ceramic bead · 200–10000 ppm range · 14.82 ADC clean air baseline"
  },
  {
    id: "dht11",
    name: "DHT11",
    title: "Digital Temperature & Humidity Probe",
    category: "sensor",
    role: "Measures ambient climate to calculate gas adsorption compensation and detect thermal runaway.",
    dataProduced: "40-bit serialized pulse stream containing temperature (°C) and relative humidity (%)",
    dataDestination: "Arduino Nano Digital Pin D2",
    busType: "Custom 1-Wire Single Bus",
    specs: "0–50 °C (±2 °C) · 20–90% RH (±5%) · 1 Hz sampling cycle"
  },
  {
    id: "arduino-nano",
    name: "Arduino Nano V3",
    title: "Dedicated Sensor Acquisition Controller",
    category: "controller",
    role: "Executes continuous 100 Hz ADC oversampling, moving-average filtering, and single-wire timing.",
    dataProduced: "Validated 16-byte structured binary telemetry packet with CRC16 checksum",
    dataDestination: "ESP32 DevKit RX2 (GPIO16) via hardware UART",
    busType: "ATmega328P Hardware UART (9600 Baud)",
    specs: "16 MHz clock · 8-channel 10-bit ADC · Isolated from Wi-Fi interrupts"
  },
  {
    id: "esp32-devkit",
    name: "ESP32 DevKit V1",
    title: "Central Safety & Logic Controller",
    category: "controller",
    role: "The master safety brain: calculates SAFE/WARNING/DANGER state machine, drives OLED & buzzer.",
    dataProduced: "State transitions, display framebuffers, 85dB alarm PWM signals, gateway payload",
    dataDestination: "OLED (I2C), Buzzer (GPIO23), ESP32-CAM Gateway (Serial)",
    busType: "Dual-Core Xtensa 240 MHz (Core 1: Safety / Core 0: UI)",
    specs: "Autonomous offline failsafe · Hysteresis filter · Zero internet dependency"
  },
  {
    id: "esp32-cam",
    name: "ESP32-CAM",
    title: "Wi-Fi Gateway & Persistence Controller",
    category: "gateway",
    role: "Handles 802.11 b/g/n Wi-Fi cloud connectivity, store-and-forward queue, and MicroSD card writes.",
    dataProduced: "HTTPS REST payload to Supabase and FAT32 CSV file writes",
    dataDestination: "Supabase Cloud Database & Local MicroSD Card",
    busType: "Wi-Fi 2.4 GHz + SPI MicroSD Bus",
    specs: "Non-blocking store-and-forward · Automatic Wi-Fi reconnection retry"
  },
  {
    id: "oled",
    name: "0.96\" OLED Display",
    title: "Monochrome Real-Time Telemetry Screen",
    category: "display",
    role: "Provides immediate at-a-glance physical telemetry: real-time PPM, climate stats, and alert status.",
    dataProduced: "Visual monochrome pixel matrix (128x64 pixels) refreshed at 10 FPS",
    dataDestination: "Direct visual feedback for nearby occupants",
    busType: "I2C Bus (Address 0x3C, SDA: GPIO21, SCL: GPIO22)",
    specs: "SSD1306 controller · High contrast in daylight or darkness · Low power"
  },
  {
    id: "buzzer",
    name: "Piezo Buzzer (85dB)",
    title: "Autonomous Physical Acoustic Siren",
    category: "actuator",
    role: "Sounds immediate audible alarm when hazardous conditions are detected, operating independent of cloud.",
    dataProduced: "Acoustic sound pressure: 2.4 kHz continuous siren or 1 Hz warning pulses",
    dataDestination: "Human auditory perception in surrounding space",
    busType: "GPIO23 Transistor-driven PWM",
    specs: "Response time < 10 ms · 85 dB at 10 cm · Driven directly by ESP32 core"
  },
  {
    id: "microsd",
    name: "MicroSD Card (16GB)",
    title: "Non-Volatile Local Data Logger",
    category: "storage",
    role: "Retains circular CSV telemetry logs locally so no data is lost during internet drops or power outages.",
    dataProduced: "CSV records: timestamp, sequence, gas PPM, temperature, humidity, safety state, CRC",
    dataDestination: "Persistent non-volatile flash storage for historical trend auditing",
    busType: "SPI Bus Interface",
    specs: "FAT32 file system · > 18 months continuous data capacity · Sector-buffered writes"
  }
];
